export const FETCH_MENU_START = 'FETCH_MENU_START';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAIL = 'FETCH_MENU_FAIL';

export const FETCH_PAGE_START = 'FETCH_PAGE_START';
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS';
export const FETCH_PAGE_FAIL = 'FETCH_PAGE_FAIL';