export const FETCH_MENU_START = 'FETCH_MENU_START';
export const FETCH_MENU_SUCCESS = 'FETCH_MENU_SUCCESS';
export const FETCH_MENU_FAIL = 'FETCH_MENU_FAIL';
export const TOGGLE_MENU = 'TOGGLE_MENU';

export const FETCH_PAGE_START = 'FETCH_PAGE_START';
export const FETCH_PAGE_SUCCESS = 'FETCH_PAGE_SUCCESS';
export const FETCH_PAGE_FAIL = 'FETCH_PAGE_FAIL';

export const SET_LIGHTBOX_IMAGES = 'SET_LIGHTBOX_IMAGES';
export const SHOW_LIGHTBOX = 'SHOW_LIGHTBOX';
export const CLOSE_LIGHTBOX = 'CLOSE_LIGHTBOX';
export const NEXT_LIGHTBOX_IMAGE = 'NEXT_LIGHTBOX_IMAGE';
export const PREVIOUS_LIGHTBOX_IMAGE = 'PREVIOUS_LIGHTBOX_IMAGE'